config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "recipes#index"

  resources :recipes do
    # 検索機能と検索結果予測
    collection do
      get 'search'
      get 'incremental_search'
    end
    # レシピの一覧のページング機能
    member do
      get 'page_next'
      get 'page_prev'
    end
    # お気に入り機能
    resources :user_likes, only: [:create, :destroy]
    # レシピ難易度評価機能
    resources :reviews, only: [:create, :destroy]
    # 調理画像の削除
    resources :cooking_images, only: :destroy
  end

  resources :users, only: :show do
    member do
      # マイページで自分のレシピの表示設定
      post 'select_publish'
      # マイページでお気に入りのレシピを表示する
      post 'favorites'
      # マイページで自分のレシピを表示する
      post 'my_recipes'
    end
  end

  resources :groups do
    member do
      # グループから退出
      delete 'exit'
      resources :group_invitations, only: [:create, :destroy]
    end
    resources :group_likes, only: [:new, :create, :destroy]
    resources :group_shoppings, only: [:show, :new, :create, :destroy]
  end

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_create :default_image
# Association
  belongs_to :user
  
  has_one_attached :image, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :cookings, dependent: :destroy
  has_many :cooking_images, dependent: :destroy

  has_many :user_likes, dependent: :destroy
  has_many :users, through: :user_likes
  
  has_many :reviews, dependent: :destroy
  
  has_many :group_likes, dependent: :destroy
  has_many :groups, through: :group_likes

# ActiveHash
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :minute
    belongs_to :serving
    belongs_to :publish

# --- Method ---

  # 料理の写真がない場合、初期画像の追加
  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('public', 'images', 'default_recipe_image.jpg')), filename: 'default_recipe_image.jpg', content_type: 'image/jpg')
    end
  end
end

app/models/recipe_form.rb
class RecipeForm
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActiveModel::Attributes

  attr_accessor :recipe_name, :recipe_image, :minute, :serving, :publish, :price, :user_id, :caution,
                :ingredient_ids, :amounts, :recipe_id,
                :contents, :cooking_images,
                :difficulty

# --- Validation -------------------------
  with_options presence: true do
    validates :recipe_name
    validates :minute
    validates :serving
    validates :publish
    validates :user_id
    validates :ingredient_ids
    validates :amounts
    validates :contents
    validates :difficulty
  end
  # ActiveHashは0を選べない
  with_options numericality: { other_than: 0, message: "は---以外を選択してください" } do
    validates :minute
    validates :serving
    validates :publish
  end
  # 値段は半角か全角の数字のみ可能
  with_options format: { with: /\A[0-9０-９]+(\.[0-9０-９]+)?\z/ } do
    validates :price, if: :blank?
  end

  # 材料(配列)のバリデーション 「---」を選択できない
  validates :ingredient_ids, ingredients: true

  # 量(配列)のバリデーション
  validates :amounts, amount: true

  # 調理方法(配列)のバリデーション
  validates :contents, content: true

  # 調理難易度は1~3以外選べない
  validates :difficulty, numericality: { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 3, message: "が正しく選択されていません" }


# --- Method ----------------------------

  def save
    recipe = Recipe.create(name: recipe_name, image: recipe_image, minute_id: minute, serving_id: serving, publish_id: publish, price: price, caution: caution, user_id: user_id)
    # 調理難易度の保存
    Review.create(difficulty: difficulty, user_id: user_id, recipe_id: recipe.id)
    i = 0
    # 材料と量を複数のレコードで保存
    ingredient_ids.each do |ingredient_id|
      amount = amounts[i]
      # 全角を半角にする
      amount.tr('０-９ａ-ｚＡ-Ｚ','0-9a-zA-Z')
      RecipeIngredient.create(ingredient_id: ingredient_id, amount: amount, recipe_id: recipe.id)
      i += 1
    end
    # 調理方法を複数のレコードで保存
    contents.each do |content|
      Cooking.create(content: content, recipe_id: recipe.id)
    end
    # 調理画像を複数のレコードで保存
    unless cooking_images.blank?
      cooking_images.each do |cooking_image|
        CookingImage.create(image: cooking_image, recipe_id: recipe.id)
      end
    end
  end

  def update
    recipe = Recipe.find(recipe_id)
    if recipe_image.blank?
      recipe.update(name: recipe_name, minute_id: minute, serving_id: serving, publish_id: publish, price: price, caution: caution, user_id: user_id)
    else
      recipe.update(name: recipe_name, image: recipe_image, minute_id: minute, serving_id: serving, publish_id: publish, price: price, caution: caution, user_id: user_id)
    end
    # 材料
    ingredients = recipe.recipe_ingredients
    pre_ingredients_length = ingredients.length
    i = 0
    # 材料と量を複数のレコードで保存
    ingredient_ids.each do |ingredient_id|
      amount = amounts[i]
      # 全角を半角にする
      amount.tr('０-９ａ-ｚＡ-Ｚ','0-9a-zA-Z')
      RecipeIngredient.create(ingredient_id: ingredient_id, amount: amount, recipe_id: recipe.id)
      i += 1
    end
    # 材料の元データの削除
    pre_ingredients_length.times do |i|
      recipe.recipe_ingredients[i].destroy
    end
    
    # 調理方法の元データの削除
    cookings = recipe.cookings
    cookings.each do |cooking|
      cooking.destroy
    end
    # 調理方法を複数のレコードで保存
    contents.each do |content|
      Cooking.create(content: content, recipe_id: recipe.id)
    end

    # 調理画像を複数のレコードで保存
    if !cooking_images.blank?
      cooking_images.each do |cooking_image|
        CookingImage.create(image: cooking_image, recipe_id: recipe.id)
      end
    end
    #調理難易度の保存
    recipe.reviews.find_by(user_id: user_id).update(difficulty: difficulty)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :page_next, :page_prev]
  before_action :set_recipe, only: [:show, :destroy, :edit, :update]
  before_action :set_recipe_page, only: [:page_next, :page_prev]
  before_action :set_recipe_step, only: [:index, :search, :page_next, :page_prev]
  before_action :redirect_index, only: :edit

  def index
    # 公開設定のレシピを作成日時が新しい順で表示
    recipes = Recipe.where(publish_id: "1").order("created_at DESC")
    @review_recipes = Recipe.where(publish_id: "1").order("created_at DESC").includes(:review)
    @page = { id: "1"}
    @recipes = recipes[0..(@step - 1)]
    @recipes_len = recipes.length
  end

  def show
    @review = Review.new
    @reviews = @recipe.reviews.where.not(user_id: @recipe.user.id).includes(:user)
  end

  def new
    @recipe = RecipeForm.new
  end

  def create
    @recipe = RecipeForm.new(recipe_params_create)
    if @recipe.valid?
      @recipe.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # @recipe_form = RecipeForm.new(recipe_name: @recipe.name, recipe_image: @recipe.image, minute: @recipe.minute.id, serving: @recipe.serving.id, publish: @recipe.publish.id, price: @recipe.price, difficulty: @recipe.reviews.find_by(user_id: current_user.id).difficulty, caution: @recipe.caution)
    @recipe_form = RecipeForm.new(recipe_name: @recipe.name, recipe_image: @recipe.image, minute: @recipe.minute.id, serving: @recipe.serving.id, publish: @recipe.publish.id, price: @recipe.price, caution: @recipe.caution)
    @ingredients = @recipe.recipe_ingredients
    @cookings = @recipe.cookings
    @cooking_images = @recipe.cooking_images
  end

  def update
    @recipe_form = RecipeForm.new(recipe_params_update)
    if @recipe_form.valid?
      @recipe_form.update
      redirect_to recipe_path(params[:id])
    else
      @ingredients = @recipe.recipe_ingredients
      @cookings = @recipe.cookings
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def search
    recipes = SearchRecipesService.search(params[:keyword])
    # レシピは9つ表示
    @page = { id: "1"}
    @recipes = recipes[0..(@step - 1)]
    @recipes_len = recipes.length
  end

  # 非同期通信の予測変換用アクション
  def incremental_search
    ingredients = SearchRecipesService.incremental_search(params[:keyword])
    render json:{ keyword: ingredients }
  end

  # レシピのページ送り機能アクション
  def page_next
    first_index = @page * @step
    last_index = ((@page + 1) * @step) - 1;
    recipes = Recipe.where(publish_id: "1").order("created_at DESC")
    @recipes_len = recipes.length
    @recipes = recipes[first_index..last_index]
  end

  def page_prev
    first_index = @page * @step
    last_index = (@page + 1) * @step - 1;
    recipes = Recipe.where(publish_id: "1").order("created_at DESC")
    @recipes_len = recipes.length
    @recipes = recipes[first_index..last_index]
  end

  private

  def recipe_params_create
    params.require(:recipe_form)
          .permit(:recipe_name, :recipe_image, :minute, :serving, :publish, :price, :difficulty, :caution, contents: [], cooking_images: [], ingredient_ids: [], amounts: [])
          .merge(user_id: current_user.id)
  end

  def recipe_params_update
    params.require(:recipe_form)
          .permit(:recipe_name, :recipe_image, :minute, :serving, :publish, :price, :difficulty, :caution, contents: [], cooking_images: [], ingredient_ids: [], amounts: [])
          .merge(user_id: current_user.id, recipe_id: params[:id])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_recipe_page
    @page = params[:id].to_i
  end
  def set_recipe_step
    @step = 9
  end

  def redirect_index
    unless user_signed_in? && current_user.id == @recipe.user_id
      redirect_to root_path
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_cooking.html.slim
.cooking
  label for="cooking_input_#{i}" style="cursor:pointer;"
    <i class="fas fa-camera" style="cursor:pointer;"></i>
  = f.file_field :cooking_image, name: "recipe_form[cooking_images][]", id: "cooking_input_#{i}", class: "cooking-inputs", style: "display:none;"
  
  = f.text_area :content, name: "recipe_form[contents][]", rows: "4", placeholder: "写真は任意です", value: content
  <i class="fas fa-times-circle remove_cooking_btn" style="cursor:pointer;"></i>

  .cooking-previews
    - unless cooking_image.blank?
      = image_tag cooking_image

app/views/recipes/_destroy.html.slim
#destroy_modal
  .modal-background
    .modal-wrapper
      .modal-container
        .modal-message
          h1 本当にこのレシピを<br>削除しますか？
        .modal-buttons
          = link_to recipe_path(recipe), class: "modal-button yes", method: :delete do
            = "はい"
          .modal-button.no id="destroy_modal_off"
            p いいえ

app/views/recipes/_ingredient_edit.html.slim
.ingredient
  = f.collection_select :ingredient_id, Ingredient.all.order("genre_id ASC"), :id, :name, { selected: ingredient.ingredient_id }, { name: "recipe_form[ingredient_ids][]", id: "ingredient_select"}
  span.amount 分量
  = f.text_field :amount, name: "recipe_form[amounts][]", value: ingredient.amount, placeholder: "数字のみ 例)100"
  <i class="fas fa-times-circle remove_btn" style="cursor:pointer;"></i>

app/views/recipes/_ingredient_new.html.slim
.ingredient
  = f.collection_select :ingredient_id, Ingredient.all.order("genre_id ASC"), :id, :name, { selected: ingredient_id }, { name: "recipe_form[ingredient_ids][]", id: "ingredient_select"}
  span.amount 分量
  = f.text_field :amount, name: "recipe_form[amounts][]", value: amount, placeholder: "数字のみ 例)100"
  <i class="fas fa-times-circle remove_btn" style="cursor:pointer;"></i>

app/views/recipes/_like_form.html.slim
- if current_user.already_liked?(recipe)
  = form_with url: "#{recipe.id}/user_likes/#{recipe.id}", method: :delete, id: "remove_like_form", remote: true do |f|
    label for="remove_like"
      <i class="fas fa-star" id="like remove_like"></i>
      = f.submit "お気に入り削除", style:"display:none;", id: "remove_like"
- else
  = form_with url: recipe_user_likes_path(recipe), remote: true do |f|
    label for="add_like"
      <i class="far fa-star" id="like add_like"></i>
      = f.submit "お気に入り追加", style:"display:none;", id: "add_like"

app/views/recipes/_pagination.html.slim
ul.pagination
  li.prev
    = link_to page_prev_recipe_path(page), remote:true, style: "visibility:hidden" do
      <i class="fas fa-arrow-left"></i>
  li.page-info
    - if recipes_len % step == 0
      - max_page = recipes_len / step
    - else
      - max_page = recipes_len / step + 1
    = "レシピ：#{recipes_len}件  ページ：#{page[:id].to_i}/#{max_page}"
  li.next
    - if recipes.length < step
      = link_to page_next_recipe_path(page), remote:true, style: "visibility:hidden" do
        <i class="fas fa-arrow-right"></i>
    - else   
      = link_to page_next_recipe_path(page), remote:true do
        <i class="fas fa-arrow-right"></i>

app/views/recipes/_recipe.html.slim
.recipe
  = link_to recipe_path(recipe) do
    .recipe-image
      = image_tag recipe.image
    .recipe-name
      = recipe.name
    table
      tbody
        tr.recipe-serving
          td.key 人数：
          td.value
            = recipe.serving.people
            p.serving-unit 人
        tr.recipe-time
          td.key 調理時間：
          td.value
            = recipe.minute.time
            p.minute-unit 分
        tr.recipe-review
          td.key 調理難易度：
          td.value
            - sum_reviews = 0
            - recipe.reviews.each do |review|
              - sum_reviews += review.difficulty.to_i
            - if recipe.reviews.present?
              - average_reviews = sum_reviews / recipe.reviews.length
              - average_reviews.times do
                <i class="fas fa-carrot"></i>

app/views/recipes/edit.html.slim
.recipe-wrapper
  .recipe-container
    .heading-name
      h1 レシピの編集

    = form_with model: @recipe_form, url: recipe_path(params[:id]), method: :patch, local: true do |f|

      = render "shared/error_messages", model: f.object

      .field.recipe-name
        label 料理名
        br
        = f.text_field :recipe_name,  placeholder: "例）カレーライス"

      .field.recipe-image
        label for="recipe_image" style="cursor:pointer;" 料理の写真を選択
          <i class="fas fa-camera" style="cursor:pointer;"></i>
        = f.file_field :recipe_image, id: "recipe_image", style: "display:none;"
        #image-preview
          = image_tag @recipe.image

      .field.recipe-time
        label 調理時間
        = f.collection_select :minute, Minute.all, :id, :time, {}, { class: "minutes" }
        p.minute 分

      .field.recipe-serving
        label 　　人数
        = f.collection_select :serving, Serving.all, :id, :people, {}
        p.people 人

      .field.recipe-ingredient
        label 材料 (15個まで)
        - @ingredients.each do |ingredient|
          = render partial: "ingredient_edit", locals: { f: f, ingredient: ingredient }
        #ingredient-space
        <i class="fas fa-plus-square" id="add_ingredient_btn" style="cursor:pointer;"></i>


      .field.recipe-cooking
        label 調理方法 (10個まで)
        br
        - i = 0
        - @cookings.each do |cooking|
          - cooking_image = @cooking_images[i].image unless @cooking_images[i].blank?
          = render partial: "cooking", locals: { f: f, content: cooking.content, i: i, cooking_image: cooking_image }
          - i += 1
        #cooking-space
        <i class="fas fa-plus-square" id="add_cooking_btn"></i>

      .field.recipe-public
        label 公開設定
        = f.collection_select :publish, Publish.all, :id, :publish, {}

      .field.recipe-price
        label 合計費用
        = f.text_field :price, placeholder: "入力は任意"
        p 円
        
      .field.recipe-difficulty
        label 調理難易度：
        = f.select :difficulty, [['かんたん', 1], ['ふつう', 2], ['むずかしい', 3]], { selected: 1 }
        
      .field.recipe-caution
        label その他(注意書きなど)：
        = f.text_area :caution, rows: "3", placeholder: "入力は任意です&#13;&#10;料理の際の注意事項や材料リストに使う材料がない場合に記載してください".html_safe

      .submit-wrapper  
        = f.submit "レシピを作る", class:"submit"

app/views/recipes/index.html.slim
main
  .content-frame
    .container
      .search-bar
        = form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |f|
          = f.text_field :keyword, placeholder: "レシピを検索", class: "search-input"
          // 予測変換用のスペース
          #search_result
          label for="search_btn"
            <i class="fas fa-search"></i>
            = f.submit "search", class: "search-btn", id: "search_btn", style:"display:none;"
      = render partial: "pagination", locals: { page: @page, step: @step, recipes: @recipes, recipes_len: @recipes_len}
      .recipes id="render_recipes"
        = render partial: "recipe", collection: @recipes
      = render partial: "pagination", locals: { page: @page, step: @step, recipes: @recipes, recipes_len: @recipes_len}

app/views/recipes/new.html.slim
.recipe-wrapper
  .recipe-container
    .heading-name
      h1 レシピの作成

    = form_with model: @recipe, url: recipes_path, local: true do |f|

      = render "shared/error_messages", model: f.object

      
      .field.recipe-name
        label 料理名
        br
        = f.text_field :recipe_name,  placeholder: "例）カレーライス"

      .field.recipe-image
        label for="recipe_image" style="cursor:pointer;" 料理の写真を選択
          <i class="fas fa-camera" style="cursor:pointer;"></i>
        = f.file_field :recipe_image, id: "recipe_image", style: "display:none;"
        #image-preview

      .field.recipe-time
        label 調理時間
        = f.collection_select :minute, Minute.all, :id, :time, {}, { class: "minutes" }
        p.minute 分

      .field.recipe-serving
        label 　　人数
        = f.collection_select :serving, Serving.all, :id, :people, {}
        p.people 人

      .field.recipe-ingredient
        label 材料 (15個まで)
        // エラー時に入力した値を保持
        - unless @recipe.ingredient_ids.blank?
          - i = 0
          - @recipe.ingredient_ids.each do |ingredient_id|
            = render partial: "ingredient_new", locals: { f: f, ingredient_id: ingredient_id, amount: @recipe.amounts[i] }
            - i += 1
        - else
          .ingredient
            = f.collection_select :ingredient_ids, Ingredient.all.order("genre_id ASC"), :id, :name, {}, { name: "recipe_form[ingredient_ids][]", id: "ingredient_select"}
            span.amount 分量
            = f.text_field :amounts, name: "recipe_form[amounts][]", placeholder: "数字のみ 例)100"
            <i class="fas fa-times-circle remove_btn" style="cursor:pointer;"></i>
        
        #ingredient-space
        <i class="fas fa-plus-square" id="add_ingredient_btn" style="cursor:pointer;"></i>


      .field.recipe-cooking
        label 調理方法 (10個まで)
        br
        // エラー時に入力した値を保持
        - unless @recipe.contents.blank?
          - i = 0
          - @recipe.contents.each do |content|
            = render partial: "cooking_new", locals: { f: f, content: content, i: i }
            - i += 1
        - else
          label for="cooking_input_0" style="cursor:pointer;"
            <i class="fas fa-camera" style="cursor:pointer;"></i>
          = f.file_field :cooking_image, name: "recipe_form[cooking_images][]", id: "cooking_input_0", class: "cooking-inputs", style: "display:none;"
          = f.text_area :content, name: "recipe_form[contents][]", rows: "4", placeholder: "写真は任意です"
          .cooking-previews
        #cooking-space
        <i class="fas fa-plus-square" id="add_cooking_btn"></i>

      .field.recipe-public
        label 公開設定
        = f.collection_select :publish, Publish.all, :id, :publish, {}

      .field.recipe-price
        label 合計費用
        = f.text_field :price, placeholder: "入力は任意"
        p 円
      
      .field.recipe-difficulty
        label 調理難易度：
        = f.select :difficulty, [['かんたん', 1], ['ふつう', 2], ['むずかしい', 3]], { selected: 1 }
      
      .field.recipe-caution
        label その他(注意書きなど)：
        = f.text_area :caution, rows: "3", placeholder: "入力は任意です&#13;&#10;料理の際の注意事項や材料リストに使う材料がない場合に記載してください".html_safe

      .submit-wrapper
        = f.submit "レシピを作る", class:"submit"

app/views/recipes/page_next.js.erb
document.getElementById('render_recipes').innerHTML = '<%= j(render partial: "recipe", collection: @recipes) %>';

var paginations = document.getElementsByClassName("pagination");
for (let i = 0; i < paginations.length; i++){
  let pagination = paginations[i];
  let prev = pagination.childNodes[0];
  let next = pagination.childNodes[2];
  let page = <%= @page %>
  prev.innerHTML = `
    <a data-remote="true" href="/recipes/${page - 1}/page_prev"><i class="fas fa-arrow-left" aria-hidden="true"></i></a>`
  next.innerHTML = `
    <a data-remote="true" href="/recipes/${page + 1}/page_next"><i class="fas fa-arrow-right" aria-hidden="true"></i></a>`;

  // 右矢印を消す
  let step = <%= @step %> 
  let sum_recipes = (page + 1) * step;
  let num_recipes = <%= @recipes_len %>
  if ( sum_recipes >= num_recipes ){
    next.setAttribute("style", "visibility:hidden;");
  };
  // 左矢印を表示させる
  if ( page != 0 ){
    prev.removeAttribute("style", "visibility:hidden;");
  };

  // ページ数を書き換える
  let current_page = pagination.childNodes[1];
  if ( num_recipes % step == 0 ) {
    max_page = Math.floor(num_recipes / step);
  }else{
    max_page = Math.floor(num_recipes / step + 1);
  };
  current_page.innerHTML = `
    レシピ：${num_recipes}件  ページ：${page + 1}/${max_page}`;
}; 

app/views/recipes/search.html.slim
main
  .content-frame
    .container
      .search-bar
        = form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |f|
          = f.text_field :keyword, placeholder: "レシピを検索", class: "search-input"
          label for="search_btn"
            <i class="fas fa-search"></i>
            = f.submit "search", class: "search-btn", id: "search_btn", style:"display:none;"
        // 予測変換用のスペース
        #search_result
      = render partial: "pagination", locals: { page: @page, step: @step, recipes: @recipes, recipes_len: @recipes_len}
      .recipes
        = render partial: "recipe", collection: @recipes
      = render partial: "pagination", locals: { page: @page, step: @step, recipes: @recipes, recipes_len: @recipes_len}

app/views/recipes/show.html.slim
.show-wrapper
  .container
    .top-wrapper
      .name-wrapper
        = @recipe.name
      .like-button id="render_like_form"
        - if user_signed_in?
          = render partial: "like_form", locals: { recipe: @recipe }

    .image-wrapper
      = image_tag @recipe.image

    .details-wrapper
      .minute-wrapper
        span 調理時間
        .info
          span.outline
            = @recipe.minute.time
          span 分
      .serving-wrapper
        span 人数
        .info
          span.outline
            = @recipe.serving.people
          span 人
      .price-wrapper
        - if @recipe.price.present?
          span 値段
          .info
            span.outline
              //全角を半角に
              = @recipe.price.tr('０-９ａ-ｚＡ-Ｚ','0-9a-zA-Z')
            span 円

    - unless @recipe.caution.blank?
      .caution-wrapper
        .caution-heading
          h2 注意書き
        .caution
          = @recipe.caution

    .ingredients-wrapper
      .ingredients-heading
        h2 材料
      .ingredients-container
        ul.ingredients
          - @recipe.ingredients.each do |ingredient|
            li.ingredient
              = ingredient.name
        ul.amounts
          - i = 0
          - @recipe.recipe_ingredients.each do |ingredient|
            li.amount
              //「tr('０-９ａ-ｚＡ-Ｚ','0-9a-zA-Z')」全角を半角に
              = ingredient.amount.tr('０-９ａ-ｚＡ-Ｚ','0-9a-zA-Z')
              // スペースを入れる
              <span> </span>
              // 量に適応した単位をつける
              - if @recipe.ingredients[i].name.include?("g")
                span g
              - elsif @recipe.ingredients[i].name.include?("個")
                span 個
              - elsif @recipe.ingredients[i].name.include?("本")
                span 本
              - elsif @recipe.ingredients[i].name.include?("cc")
                span cc
              - elsif @recipe.ingredients[i].name.include?("枚")
                span 枚
              - elsif @recipe.ingredients[i].name.include?("大さじ")
                span 杯(大さじ)
              - elsif @recipe.ingredients[i].name.include?("小さじ")
                span 杯(小さじ)
              - elsif @recipe.ingredients[i].name.include?("キューブ")
                span キューブ
              - elsif @recipe.ingredients[i].name.include?("パック")
                span パック
              - elsif @recipe.ingredients[i].name.include?("片")
                span 片
              - i += 1
    .cookings-wrapper
      .cookings-heading
        h2 調理方法
      .cookings-container
        ul.cookings
          - @recipe.cookings.each do |cooking|
            li.cooking
              = cooking.content
        - unless @recipe.cooking_images.blank?
          ul.cooking-images
            - @recipe.cooking_images.each do |cooking_image|
              li.cooking-image
                = image_tag cooking_image.image
                - if user_signed_in? && current_user.id == @recipe.user_id
                  = link_to recipe_cooking_image_path(@recipe, cooking_image), method: :delete do
                    <i class="fas fa-times-circle" style="cursor:pointer;"></i>

    .buttons-wrapper
      - if user_signed_in? && current_user.id == @recipe.user_id
        .edit-button-wrapper
          = link_to edit_recipe_path(@recipe), class: "edit-button btn" do
            = "編集する"
        .destroy-button-wrapper
          p.destroy-button.btn id="show_destroy_modal" 削除する

    .reviews-wrapper
      .review-heading
        h1 レシピのレビュー
      - if user_signed_in?
        .review-form
          - if current_user.commentable?(@recipe)
            = form_with model: @review, url: recipe_reviews_path(@recipe) do |f|
              = f.text_area :comment, row: "2", placeholder: "コメントを入力する"
              .difficulty-title 調理難易度選択：
              = f.select :difficulty, [['かんたん', 1], ['ふつう', 2], ['むずかしい', 3]]
              = f.submit "送信", class: "submit"
      - if @reviews.exists?
        ul.comments-wrapper
          - @reviews.each do |review|
            li.review
              p.difficulty 
                | レビュー難易度：
                - review.difficulty.times do
                  <i class="fas fa-carrot"></i>
              p.user 
                | 投稿者：
                = "#{review.user.nick_name}さん"
              - if user_signed_in? && review.user.id == current_user.id
                = link_to "削除する", recipe_review_path(@recipe, review.id), method: :delete, class: "review-destroy"
              - if review.comment
                .comment
                  = review.comment
              - else
                .comment
                  = "コメントはありません"

= render partial: "destroy", locals: { recipe: @recipe }