config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "recipes#index"

  resources :recipes do
    # 検索機能と検索結果予測
    collection do
      get 'search'
      get 'incremental_search'
    end
    # レシピの一覧のページング機能
    member do
      get 'page_next'
      get 'page_prev'
    end
    # お気に入り機能
    resources :user_likes, only: [:create, :destroy]
    # レシピ難易度評価機能
    resources :reviews, only: [:create, :destroy]
    # 調理画像の削除
    resources :cooking_images, only: :destroy
  end

  resources :users, only: :show do
    member do
      # マイページで自分のレシピの表示設定
      post 'select_publish'
      # マイページでお気に入りのレシピを表示する
      post 'favorites'
      # マイページで自分のレシピを表示する
      post 'my_recipes'
    end
  end

  resources :groups do
    member do
      # グループから退出
      delete 'exit'
      resources :group_invitations, only: [:create, :destroy]
    end
    resources :group_likes, only: [:new, :create, :destroy]
    resources :group_shoppings, only: [:show, :new, :create, :destroy]
  end

end

app/models/group.rb
class Group < ApplicationRecord
# Association
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_one :group_owner, dependent: :destroy
  has_one :owner, through: :group_owner, source: :user, dependent: :destroy
  has_many :group_invitations, dependent: :destroy
  has_many :invited_users, through: :group_invitations, source: :user, dependent: :destroy
  has_many :group_likes, dependent: :destroy
  has_many :recipes, through: :group_likes
  has_one :group_shopping, dependent: :destroy

# Validation
  validates :name, presence: true
end

app/models/group_form.rb
class GroupForm
  include ActiveModel::Model
  include ActiveModel::Validations
  include ActiveModel::Attributes

  attr_accessor :group_name, :user_names, :current_user_id, :group_id

# Validation
  with_options presence: true do
    validates :group_name
    validates :user_names, if: :blank?
  end
  # 存在しないユーザーID && 空の保存ができない（配列版）
  validates :user_names, invite_user: { attr: 'group_id' }

# Method
  def save
    group = Group.create(name: group_name)
    GroupOwner.create(group_id: group.id, user_id: current_user_id)
    user = UserGroup.create(group_id: group.id, user_id: current_user_id)
    user_names.each do |user_name|
      user = User.find_by(user_name: user_name)
      GroupInvitation.create(user_id: user.id, group_id: group.id)
    end
  end

  def update
    group = Group.find(group_id)
    group.update(name: group_name)
    unless user_names.blank?
      user_names.each do |user_name|
        user = User.find_by(user_name: user_name)
        GroupInvitation.create(user_id: user.id, group_id: group.id)
      end
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy, :exit]
  
  def index
    user = User.find(current_user.id)
    @invited_groups = user.invited_groups
    @groups = user.groups.includes(:users)
  end
  
  def show
    @recipes = @group.recipes.includes(:reviews)
  end

  def new
    @group_form = GroupForm.new
  end

  def create
    @group_form = GroupForm.new(group_form_params)
    if @group_form.valid?
      @group_form.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group_form = GroupForm.new(group_name: @group.name)
  end

  def update
    @group_form = GroupForm.new(group_form_params_update)
    if @group_form.valid?
      @group_form.update
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  def exit
    user_group = UserGroup.find_by(user_id: current_user.id, group_id: @group.id)
    user_group.destroy
    # オーナーが脱退した際に次のユーザーがオーナーに自動でなります。
    if @group.owner.id == current_user.id
      GroupOwner.find_by(user_id: current_user.id, group_id: @group.id).destroy
      if @group.users[0]
        GroupOwner.create(user_id: @group.users[0].id, group_id: @group.id)
      else
        @group.destroy
      end
    end
    redirect_to groups_path
  end

  private
  def group_form_params
    params.require(:group_form).permit(:group_name, user_names: []).merge(current_user_id: current_user.id)
  end
  def group_form_params_update
    params.require(:group_form).permit(:group_name, user_names: []).merge(current_user_id: current_user.id, group_id: params[:id])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_destroy.html.slim
#destroy_modal
  .modal-background
    .modal-wrapper
      .modal-container
        .modal-message
          h1 本当にこのグループを<br>削除しますか？
        .modal-buttons
          = link_to group_path(group), class: "modal-button yes", method: :delete do
            = "はい"
          .modal-button.no id="destroy_modal_off"
            p いいえ

app/views/groups/_exit.html.slim
#destroy_modal
  .modal-background
    .modal-wrapper
      .modal-container
        .modal-message
          h1 本当にこのグループを<br>脱退しますか？
        .modal-buttons
          = link_to exit_group_path(group), class: "modal-button yes", method: :delete do
            = "はい"
          .modal-button.no id="destroy_modal_off"
            p いいえ

app/views/groups/_recipe.html.slim
.recipe
  = link_to group_group_like_path(group, recipe), method: :delete do
    <i class="fas fa-times-circle" style="cursor:pointer;"></i>
  = link_to recipe_path(recipe) do
    .recipe-image
      = image_tag recipe.image
    .recipe-name
      = recipe.name
    table
      tbody
        tr.recipe-serving
          td.key 人数：
          td.value
            = recipe.serving.people
            p.serving-unit 人
        tr.recipe-time
          td.key 調理時間：
          td.value
            = recipe.minute.time
            p.minute-unit 分
        tr.recipe-review
          td.key 調理難易度：
          td.value
            - sum_reviews = 0
            - recipe.reviews.each do |review|
              - sum_reviews += review.difficulty.to_i
            - if recipe.reviews.present?
              - average_reviews = sum_reviews / recipe.reviews.length
              - average_reviews.times do
                <i class="fas fa-carrot"></i>

app/views/groups/_user_name.html.slim
.invite-user
  = f.text_field :user_id, placeholder: "招待したいユーザーのIDを入力してください", name: "group_form[user_names][]", value: user_name
  <i class="fas fa-times-circle remove_user_btn" style="cursor:pointer;"></i>

app/views/groups/edit.html.slim
// グループ作成とほぼ一緒
.new-group-wrapper
  .container
    .new-group-heading-wrapper
      .new-group-heading
        h1 グループの編集

    = form_with model: @group_form, url: group_path, method: :put, local: true, class: "group-form" do |f|
      = render "shared/error_messages", model: f.object
      .group-name-wrapper
        .group-name-heading
          h2 グループ名
        .group-name-form 
          = f.text_field :group_name, placeholder: "グループを入力してください", name: "group_form[group_name]"
      .invite-user-wrapper
        .invite-user-heading
          h2 ユーザーをグループに追加で招待する
        // エラー時に入力した値を保持
        - unless @group_form.user_names.blank?
          -  @group_form.user_names.each do |user_name|
            = render partial: "user_name", locals: { f: f, user_name: user_name}
        #invite-user-space
        <i class="fas fa-plus-square" id="add_invite_user_btn"></i>
      .submit-btn-wrapper
        = f.submit "グループ作成", class: "submit-btn"

app/views/groups/index.html.slim
.group-wrapper
  .container
    .group-heading-wrapper
      .group-heading
        h1 グループ
    - unless @invited_groups.blank?
      .group-invitations-wrapper
        .group-invitations-title
          h2 グループの招待リスト
        ul.group-invitations
          - @invited_groups.each do |invited_group|
            li.group-invitation
              .group-info
                = "#{invited_group.name}に招待されています"
              .group-buttons
                = link_to "参加する", group_invitations_path(invited_group), method: :post, class: "join"
                = link_to "断る", group_invitation_path(invited_group), method: :delete, class: "decline"
    .groups-list-wrapper
      .groups-list-title
        h2 グループ一覧
      .groups-list-columns
        .add-recipe-column
        .group-name-column
          h3 グループ名
        .group-member-column
          h3 参加人数
        .group-owner-column
          h3 オーナー
        .group-buttons-column
      ul.groups
        - unless @groups.blank?
          - @groups.each do |group|
            li.group
              .add-recipe
                = link_to "レシピを追加する", new_group_group_like_path(group), class: "add-recipe-btn"
              .group-name
                = link_to group_path(group), class: "group-name-link" do 
                  = group.name
              .group-member
                .group-member-num
                  = group.users.length
              .group-owner
                .group-owner-name
                  = "#{group.owner.nick_name}さん"
              .group-buttons
                = link_to "編集", edit_group_path(group), class: "edit"
                - if current_user.id == group.owner.id
                  p.destroy style="cursor:pointer;" id="show_destroy_modal"
                    | 削除する
                  = render partial: "destroy", locals: { group: group }
    .new-group-btn-wrapper
      = link_to "グループを作成する", new_group_path, class: "new-group-btn"

app/views/groups/new.html.slim
.new-group-wrapper
  .container
    .new-group-heading-wrapper
      .new-group-heading
        h1 グループの作成

    = form_with model: @group_form, url: groups_path, local: true, class: "group-form" do |f|
      = render "shared/error_messages", model: f.object
      .group-name-wrapper
        .group-name-heading
          h2 グループ名
        .group-name-form 
          = f.text_field :group_name, placeholder: "グループを入力してください", name: "group_form[group_name]"
      .invite-user-wrapper
        .invite-user-heading
          h2 ユーザーをグループに招待する
        // エラー時に入力した値を保持
        - unless @group_form.user_names.blank?
          -  @group_form.user_names.each do |user_name|
            = render partial: "user_name", locals: { f: f, user_name: user_name}
        - else
          .invite-user
            = f.text_field :user_id, placeholder: "招待したいユーザーのIDを入力してください", name: "group_form[user_names][]"
        #invite-user-space
        <i class="fas fa-plus-square" id="add_invite_user_btn"></i>
      .submit-btn-wrapper
        = f.submit "グループ作成", class: "submit-btn"

app/views/groups/show.html.slim
.group-show-wrapper
  .container
    .group-show-heading-wrapper
      .group-show-heading
        = @group.name
      .calender-link-wrapper
        - if @group.group_shopping.nil?
          = link_to new_group_group_shopping_path(@group) do
            <i class="far fa-calendar-alt"></i>買い物リスト作成へ
        - else
          = link_to group_group_shopping_path(@group, @group.group_shopping) do
            <i class="far fa-calendar-alt"></i>買い物リストへ
    .group-member-list-wrapper
      .group-member-heading
        .group-member-title
          h2 メンバー
        .group-member-num-wrapper
          .group-member-num
            = "#{@group.users.length}人"
      ul.group-member-list
        - @group.users.each do |user|
          li.group-member
            = "#{user.nick_name}さん"
            
    #render_group_recipe
      .group-recipe-heading-wrapper
        .group-recipe-heading
          h2 グループレシピ
        .add-group-recipe-btn-wrapper
          = link_to "レシピを追加する", new_group_group_like_path(@group), class: "add-group-recipe"
      .group-recipes-wrapper
        .recipes
          = render partial: "recipe", collection: @recipes, locals: { group: @group }

    .exit-group-btn-wrapper
      p.exit-group-btn id="show_destroy_modal" style="cursor:pointer;"
        | 脱退する
      = render partial: "exit", locals: { group: @group }