config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "recipes#index"

  resources :recipes do
    # 検索機能と検索結果予測
    collection do
      get 'search'
      get 'incremental_search'
    end
    # レシピの一覧のページング機能
    member do
      get 'page_next'
      get 'page_prev'
    end
    # お気に入り機能
    resources :user_likes, only: [:create, :destroy]
    # レシピ難易度評価機能
    resources :reviews, only: [:create, :destroy]
    # 調理画像の削除
    resources :cooking_images, only: :destroy
  end

  resources :users, only: :show do
    member do
      # マイページで自分のレシピの表示設定
      post 'select_publish'
      # マイページでお気に入りのレシピを表示する
      post 'favorites'
      # マイページで自分のレシピを表示する
      post 'my_recipes'
    end
  end

  resources :groups do
    member do
      # グループから退出
      delete 'exit'
      resources :group_invitations, only: [:create, :destroy]
    end
    resources :group_likes, only: [:new, :create, :destroy]
    resources :group_shoppings, only: [:show, :new, :create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
# --- アソシエーション ---
  has_many :recipes
  has_many :user_likes
  has_many :favorites, through: :user_likes, source: :recipe
  has_many :reviews
  
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :group_owners
  has_many :own_groups, through: :group_owners, source: :group
  has_many :group_invitations
  has_many :invited_groups, through: :group_invitations, source: :group
  
# --- バリデーション ---
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable,
          :authentication_keys => [:user_name]

  # case_sensitiveはRSpecテスト用
  with_options presence: true, uniqueness: { case_sensitive: true } do
    validates :nick_name
    validates :user_name
  end

  validates :user_name, format: { with: /\A[a-zA-Z\d]{4,16}\z/i, message: "が正しくありません"}

# --- Method ---
  
# 投稿者本人と既にレビューした人はコメントできません
  def commentable?(recipe)
    if self.reviews.exists?(recipe_id: recipe[:id])
      return false
    elsif recipe.user.id == self.id
      return false
    else
      return true
    end
  end

  # お気に入り済みか判断
  def already_liked?(recipe)
    self.user_likes.exists?(recipe_id: recipe[:id])
  end

  # Remember_meを常にTrue
  def remember_me
    true
  end
  #usernameを利用してログインするようにオーバーライド
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      #認証の条件式を変更する
      where(conditions).where(["username = :value", { :value => user_name }]).first
    else
      where(conditions).first
    end
  end
# メールアドレスを使わない設定
  def email_required?
    false
  end
  def email_changed?
    false
  end
  def will_save_change_to_email?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_index, only: :show
  before_action :set_user

  def show
    redirect_index
    @recipes = @user.recipes.order("created_at DESC")
  end

  # マイレシピを「全部、公開、非公開」でレシピの表示を変える
  def select_publish
    select_id = params[:select_publish_form][:publish]
    case select_id
    when "1"
      @recipes = @user.recipes.order("created_at DESC")
    when "2"
      @recipes = @user.recipes.where(publish_id: 1).order("created_at DESC")
    when "3"
      @recipes = @user.recipes.where(publish_id: 2).order("created_at DESC")
    end
  end
  
  # お気に入りのレシピを表示させる
  def favorites
    @liked_recipes = @user.favorites.order("created_at DESC")
  end
  # マイレシピを表示させる
  def my_recipes
    @recipes = @user.recipes.order("created_at DESC")
  end

  private
  def redirect_index
    unless current_user.id == params[:id].to_i
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_my_favorite_recipes.html.slim
.liked-recipes-heading
  p.favorite-title お気に入りのレシピ
.liked-recipes-wrapper
  .liked-recipes
    =render partial: "recipes/recipe", collection: liked_recipes

app/views/users/_my_recipes.html.slim
.my-recipes
  .user-recipes-heading
    = "#{@user.nick_name}さんのレシピ"
    = form_with url: select_publish_user_path(@user), remote: true, id: "select_publish_form" do |f|
      = f.select :publish, [['全部', 1], ['公開', 2], ['非公開', 3]], {}, { name: "select_publish_form[publish]"}
      = f.submit "送信", id: "publish_submit", style: "display:none"
  .recipes id="render_recipes"
    = render partial: "recipes/recipe", collection: recipes

app/views/users/favorites.js.erb
document.getElementById('render_mypage_recipes').innerHTML = '<%= j(render partial: "my_favorite_recipes", locals: { liked_recipes: @liked_recipes }) %>';
var user_id = <%= @user.id %>;
document.getElementById('mypage-toggle').innerHTML = `
<a class="link-my-recipes" data-turbolinks="true" data-remote="true" rel="nofollow" data-method="post" href="/users/${user_id}/my_recipes"><i class="fas fa-book" aria-hidden="true"></i>マイレシピへ</a>`;

app/views/users/my_recipes.js.erb
document.getElementById('render_mypage_recipes').innerHTML = '<%= j(render partial: "my_recipes", locals: { recipes: @recipes }) %>';
var user_id = <%= @user.id %>;
document.getElementById('mypage-toggle').innerHTML = `
<a class="link-favorites" data-turbolinks="true" data-remote="true" rel="nofollow" data-method="post" href="/users/${user_id}/favorites"><i class="fas fa-star" aria-hidden="true"></i>お気に入りレシピへ</a>`;


if (document.getElementById("publish")){
  const select_form = document.getElementById("publish");
  select_form.addEventListener('change', (e) => {
    const submit_btn = document.getElementById("publish_submit");
    submit_btn.click();
  });
};

app/views/users/select_publish.js.erb
document.getElementById('render_recipes').innerHTML = '<%= j(render partial: "recipes/recipe", collection: @recipes) %>';

app/views/users/show.html.slim
.user-show-wrapper
  .container
    .heading
      h1 マイページ
      #mypage-toggle
        = link_to favorites_user_path(@user), method: :post, remote: true, class: "link-favorites", data: {"turbolinks"=>true} do
          <i class="fas fa-star"></i>
          = "お気に入りレシピへ"
        / = link_to my_recipes_user_path(@user), method: :post, remote: true, class: "link-my-recipes" data: {"turbolinks"=>true} do
        /   <i class="fas fa-book"></i>
        /   = "マイレシピへ"
    #render_mypage_recipes
      = render partial: "my_recipes", locals: { recipes: @recipes }