config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "recipes#index"

  resources :recipes do
    # 検索機能と検索結果予測
    collection do
      get 'search'
      get 'incremental_search'
    end
    # レシピの一覧のページング機能
    member do
      get 'page_next'
      get 'page_prev'
    end
    # お気に入り機能
    resources :user_likes, only: [:create, :destroy]
    # レシピ難易度評価機能
    resources :reviews, only: [:create, :destroy]
    # 調理画像の削除
    resources :cooking_images, only: :destroy
  end

  resources :users, only: :show do
    member do
      # マイページで自分のレシピの表示設定
      post 'select_publish'
      # マイページでお気に入りのレシピを表示する
      post 'favorites'
      # マイページで自分のレシピを表示する
      post 'my_recipes'
    end
  end

  resources :groups do
    member do
      # グループから退出
      delete 'exit'
      resources :group_invitations, only: [:create, :destroy]
    end
    resources :group_likes, only: [:new, :create, :destroy]
    resources :group_shoppings, only: [:show, :new, :create, :destroy]
  end

end

app/views/shared/_footer.html.slim
footer
  .footer-left
    / a href="#"
    /   i class="far fa-envelope"
    /   | メールでお問い合わせ
    .donate
      / i class="fas fa-donate"
      / = link_to "開発者に寄付する", "#"
  .footer-right
    .footer-logo
      h1 ShaRecipe

app/views/shared/_header.html.slim
header
  .header-left
    .header-logo
      = link_to "ShaRecipe", root_path
  .header-right
    ul.header-buttons
      - if user_signed_in?
        li.header-btn 
          = link_to "#{current_user.nick_name}さん", user_path(current_user)
        li.header-btn 
          = link_to "グループ", groups_path
        li.header-btn 
          = link_to "レシピ投稿", new_recipe_path
        li.header-btn 
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        li.header-btn 
          = link_to "ログイン", new_user_session_path
        li.header-btn 
          = link_to "アカウント作成", new_user_registration_path